/// Flutter icons SobreroIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SobreroIcons
///      fonts:
///       - asset: fonts/SobreroIcons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class SobreroIcons {
  SobreroIcons._();

  static const _kFontFam = 'SobreroIcons';
  static const _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData content1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_arrow = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xf024, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout2 = IconData(0xf02d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled_alt = IconData(0xf086, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData net_error = IconData(0xf127, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation = IconData(0xf19d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData student = IconData(0xf501, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint = IconData(0xf577, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData content2 = IconData(0xf658, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
