/// Flutter icons SobreroIcons2
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SobreroIcons2
///      fonts:
///       - asset: fonts/SobreroIcons2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SobreroIcons2 {
  SobreroIcons2._();

  static const _kFontFam = 'SobreroIcons2';
  static const _kFontPkg = null;

  static const IconData heart = IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xf005, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alternate_list = IconData(0xf022, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xf024, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xf044, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xf07b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open = IconData(0xf07c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments = IconData(0xf086, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hdd = IconData(0xf0a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = IconData(0xf0e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiling_face = IconData(0xf118, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building = IconData(0xf1ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xf1d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sticky_note = IconData(0xf249, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xf279, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handshake = IconData(0xf2b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_circle = IconData(0xf2bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData identification_badge = IconData(0xf2c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alternate_trash = IconData(0xf2ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
