// Copyright 2020 I.S. "A. Sobrero". All rights reserved.
// Use of this source code is governed by the GPL 3.0 license that can be
// found in the LICENSE file.

String licenseHTML = "Ultimo aggiornamento 23 luglio 2020<p>Grazie per aver "
    "scelto mySobrero, i presenti termini di utilizzo (di seguito “Condizioni”)"
    " regolano l’uso dell’app mySobrero (di seguito “App”) nonché dei Servizi "
    "che essa offre. Scaricando, installando o utilizzando l’App, o utilizzando"
    " i Servizi offerti da essa in qualsiasi modo, confermi di aver letto e "
    "compreso il contenuto dei presenti Termini di Utilizzo e ne accetti i "
    "termini.</p><h1>I. Informazioni Generali</h1><p>mySobrero è una nuova app "
    "pensata appositamente per gli studenti del Sobrero, digitalizzando "
    "ulteriormente la vita studentesca raccogliendo in un unico posto il "
    "Registro Elettronico, le notizie della scuola, sondaggi interni, una "
    "piattaforma di compravendita libri e altre esperienze.</p><p>L’App "
    "utilizza i dati a disposizione (come i dati anagrafici, corso frequentato,"
    " classe, obbiettivi per la pagella finale ecc.) per personalizzare "
    "l’esperienza dell’Utente.</p><h1>II. Licenza</h1><p>L’App ti viene "
    "concessa in licenza ai sensi della GNU General Public License Version 3.0,"
    " fatte salve componenti e librerie open source usate dall’App che sono "
    "coperte da licenze open source diverse.<br>La lista di queste librerie, "
    "e le relative licenze, è disponibile nella repository principale dell’App "
    "disponibile su GitHub.</p><p>Alcune componenti dell’App sono closed "
    "source, queste vengono concesse in licenza, ovvero all’utente viene "
    "concesso il diritto di installare ed eseguire una istanza del componente "
    "sul dispositivo in uso, che può essere usato da una persona alla volta. "
    "Le componenti closed source sono coperte dal diritto del copyright e "
    "queste non possono essere né decompilate né divulgate in ogni loro "
    "particolare.</p><h1>III. Servizi e materiali di terze parti</h1><p>"
    "L’App può consentire l’accesso a servizi e siti web dell’I.S. “A. Sobrero”"
    " o di terze parti (complessivamente e individualmente indicati come "
    "“Servizi”). L’utilizzo dell’App e dei Servizi può richiedere l’accesso a "
    "Internet o l’accesso a servizi di terze parti.</p><h1>IV. Accesso ad "
    "Internet e tariffe generali</h1><p>L’App viene messa a disposizione sugli"
    " app store a titolo gratuito. Tu sei il solo responsabile del pagamento "
    "di qualsiasi altro costo o spesa relativi all’utilizzo dell’App, inclusi "
    "eventuali costi relativi all’accesso alla rete Internet.</p><h1>V. Gli "
    "impegni dell'utente nei confronti di mySobrero</h1><p>mySobrero è nato "
    "per migliorare la vita degli studenti del Sobrero, rispettando la loro "
    "sicurezza e privacy.</p>Tutti questi servizi vengono offerti gratuitamente"
    " agli studenti. In cambio l’utente deve assumersi i seguenti impegni:<ul>"
    " <li>L’utente non può utilizzare l’App per ledere diritti di terzi o porre"
    " in essere condotte illecite</li><li>L’utente non può utilizzare l’App se "
    "minore di 14 anni. Se l’utente ha almeno 14 anni ma minorenne, non può "
    "utilizzare l’App se non dispone dell’autorizzazione di un genitore o di "
    "chi esercita la sua rappresentanza legale.</li><li>L’utente non può "
    "decompilare l’app dello store, ma può utilizzare il codice sorgente "
    "disponibile online per distribuire una propria versione</li><li> L’utente "
    "non può usare l’App per condividere elementi: <ul> <li>Contrari alle "
    "Condizioni</li><li>Contrari alla legge, ingannevoli, discriminatori o "
    "fraudolenti</li><li>In violazione o contrari ai diritti di altri soggetti."
    "</li></ul> </li><li>L’utente non può distribuire una versione dell’App "
    "contenente codice malevolo</li><li>L’utente non può distribuire una "
    "versione dell’App personalizzata sotto il nome di mySobrero</li><li>"
    "L’utente non può eseguire codice dannoso sui server di supporto dell’App"
    "</li><li>L’utente non può accedere ai dati dei server di supporto dell’App"
    " se non tramite l’App stessa o le API di supporto</li></ul><p>Ove "
    "opportuno, verranno adottati provvedimenti nei confronti dell’account "
    "dell’utente (es. ban dell’utente), informando lo stesso dell’accaduto e "
    "delle cause relative alla decisione.</p><p>Per supportare la comunità "
    "studentesca, incoraggiamo l’utente a segnalare contenuti o condotte "
    "ritenuti contrari ai propri diritti o alle nostre Condizioni o normative."
    "</p><h1>VI. Sicurezza della piattaforma</h1><p>mySobrero è stato "
    "sviluppato rispettando i più alti standard di sicurezza attuali, ciò "
    "nonostante nessun sistema informatico è sicuro al 100%.<br>L’utente è "
    "tenuto a segnalare eventuali falle di sicurezza dell’App o del server di "
    "supporto al team di sviluppo, ogni abuso della piattaforma è punito.</p>"
    "<h1>VII. Ulteriori disposizioni</h1><p>Lavoriamo costantemente per "
    "ottimizzare i nostri Servizi e per sviluppare nuove funzioni in grado di "
    "migliorare l’App. Pertanto, potremmo dover aggiornare periodicamente tali "
    "Condizioni per indicare in modo preciso i nostri servizi e le nostre "
    "pratiche. Salvo quanto diversamente previsto dalla legge, l'utente verrà "
    "informato riguardo eventuali modifiche alle presenti Condizioni. Una "
    "volta entrati in vigore tutti i Termini aggiornati, l'utente dovrà "
    "rispettarli se continua a usare l’App.</p>";
